// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ME_EquipActor","status":true,"description":"This plugin allows you to equip items as party members","parameters":{}}
];
